let
    Источник = Excel.Workbook(Параметр1, null, true),
    #"Строки с примененным фильтром" = Table.SelectRows(Источник, each ([Kind] = "Table")),
    #"Строки с примененным фильтром2" = Table.SelectRows(#"Строки с примененным фильтром", each ([Name] = Пример1ТаблицыПланаГОРИЗ)),
    ТаблицаДругиеУдаленныеСтолбцы = Table.SelectColumns(#"Строки с примененным фильтром2",{"Data"}),
    КолонкиТаблицы = Table.ColumnNames(ТаблицаДругиеУдаленныеСтолбцы{0}[Data]),
    РазвернутыйэлементData = Table.ExpandTableColumn(ТаблицаДругиеУдаленныеСтолбцы, "Data", КолонкиТаблицы),
    Пользовательский1 = Table.RemoveColumns(РазвернутыйэлементData,{"Наименование подразделения", "Наименование источника", "Наименование направления", "Основание операции", "Дт Наименование субконто", "Кт Наименование субконто", "Всп поле 1", "Всп поле 2", "Сумма движения", "Наименование организации"}),
    #"Заполнение вниз" = Table.FillDown(Пользовательский1,{"Код подразделения", "Код источника", "Код направления", "Код организации"}),
    #"Строки с примененным фильтром5" = Table.SelectRows(#"Заполнение вниз", each ([Дт Счет] <> null) and ([Кт Счет] <> null)),
    #"Другие столбцы с отмененным свертыванием" = Table.UnpivotOtherColumns(#"Строки с примененным фильтром5", {"Код организации", "Код подразделения", "Код источника", "Код направления", "Контрагент в операции", "Наименование операции", "Дт Счет", "Дт Код субконто", "Кт Счет", "Кт Код субконто", "Код НДС"}, "Атрибут", "Значение"),
    #"Строки с примененным фильтром3" = Table.SelectRows(#"Другие столбцы с отмененным свертыванием", each ([Значение] <> null and [Значение] <> 0 and [Значение] <> "")),
    #"Строки с примененным фильтром4" = Table.SelectRows(#"Строки с примененным фильтром3", each [Дт Счет] <> null and [Дт Счет] <> ""),
    Строкиспримененнымфильтром5 = Table.SelectRows(#"Строки с примененным фильтром4", each [Кт Счет] <> null and [Кт Счет] <> ""),
    #"Переименованные столбцы" = Table.RenameColumns(Строкиспримененнымфильтром5,{{"Атрибут", "Дата проводки"}, {"Значение", "Сумма проводки"}})
in
    #"Переименованные столбцы"